import "./globals.css";
// import { Inter } from "next/font/google";
import "antd/dist/reset.css";

import {
  NextAuthProvider,
  RootStyleRegistry,
  StoreProvider,
  AntDProvider,
} from "../components/Provider";
// import AppBar from "@/components/AppBar";
import LayoutAdmin from "@/components/Layout/Admin";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body>
        <Analytics />
        <RootStyleRegistry>
          <NextAuthProvider>
            <StoreProvider>
              <AntDProvider>{children}</AntDProvider>
            </StoreProvider>
          </NextAuthProvider>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
